### ISSUE TITLE
.validate is not a function - Laravel 5.3

### ISSUE THREAD

**Issue by rhonz10** [proengsoft/laravel-jsvalidation#184]
`Uncaught TypeError: "#frm_page-create".validate is not a function`

This package worked on my previous project with Laravel 5.2 but now I'm using 5.3 and it's not working.

I know that '.validate is not a function' error is caused by missing jquery.validate.js library but then this package is already shipped with a custom version of jquery.validate.js.

`$validator = JsValidatorFacade::make($this->rules, $this->messages,[],'#frm_page-create');`
`return view('admin.pages.create',compact('validator'));`

JsValidator facade alias does not work even though it is already defined in config/app.php

jsvalidation script is also present on my view.

`<script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>`
`{!! $validator !!}`

**Comment by torrentalle** [comment]
Hi,

To get work the Facade you can simply add `use JsValidator;` in your class

```php
<?php
namespace App\Http\Controllers;
use JsValidator;

class MyController extends Controller {
    public function form() {
        $validator = JsValidator::make(['type_list'=>'required']);
    }
}
```

**Comment by torrentalle** [comment]
I' can't reproduce your javascript issue. 
Can you test your code `master` branch? I made some fixes to support Laravel 5.3; maybe your issue is related to others

**Comment by rhonz10** [comment]
My mistake. This works on Laravel 5.3. It took me sometime to figure it out. It was a typo error i made on the bootstrap.php file.
